kind = "api"
  previewPath = "/"
  title = "Synapse"
  version = "1.0.0"
  id = "3B4_FFSkEVBkAeYMFRJ2e"

  [[services]]
  localPort = 8080
  name = "Synapse"
  paths = ["/"]

  [services.development]
  run = "echo 'Synapse is user-managed on port 8080'"
